# Generated by Django 5.2.18 on 2026-10-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salitaaco', '0004_move_profiles_to_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
