# Generated by Django 5.2.18 on 2026-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salitaaco', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='tile_size',
            field=models.CharField(choices=[('small', 'Maliit'), ('medium', 'Katamtaman'), ('large', 'Malaki')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='childaccount',
            name='tile_size',
            field=models.CharField(choices=[('small', 'Maliit'), ('medium', 'Katamtaman'), ('large', 'Malaki')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='guardianaccount',
            name='tile_size',
            field=models.CharField(choices=[('small', 'Maliit'), ('medium', 'Katamtaman'), ('large', 'Malaki')], default='medium', max_length=10),
        ),
    ]
