# Generated by Django 5.2.18 on 2026-10-10 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salitaaco', '0006_account_tile_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyVoice',
            fields=[
                ('family_voice_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('elevenlabs_voice_id', models.CharField(max_length=100)),
                ('consent_at', models.DateTimeField()),
                ('consent_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_voices', to='salitaaco.guardianaccount')),
            ],
        ),
        migrations.AddField(
            model_name='childaccount',
            name='family_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='salitaaco.familyvoice'),
        ),
    ]
